/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MarsRover {
  constructor();
  setTime(time: number): void;
  setSequence(seq: number): void;
  getLedgerInfo(): string;
  fundAccount(account: string, balance: number): void;
  getAccount(account: string): string;
  getBalance(account: string): string;
  simulateTx(transactionEnvelope: string): string;
  sendTransaction(transactionEnvelope: string): string;
  networkPassphrase(): string;
  getNetworkInfo(): string;
  getContractData(contractAddress: string, key: string, durability: string): string;
  getTransaction(hash: string): string;
}
